#!/bin/bash

FOLDER="$1"
if [ "$FOLDER" = "1" ] ; then
    FOLDER="sift_lowe"
else 
    if [ "$FOLDER" = "2" ] ; then
        FOLDER="sift_vlfeat"
    else 
        if [ "$FOLDER" = "3" ] ; then
            FOLDER="open_surf"
        fi
    fi
fi

cd $FOLDER/pmvs/models/
meshlab option-0000.ply 
cd ../..
