#!/bin/bash
# This file runs all the necessary commands to bundle 

#define some paths
INSTALLS="$HOME/Installs_64"
BUNDLER_PATH="$INSTALLS/bundler0.4-std"
BUNDLER_BIN="$BUNDLER_PATH/bin"
BUNDLE2PMVS="$BUNDLER_BIN/Bundle2PMVS"
CMVS="$INSTALLS/cmvs-std/program/main"
EXTRACT_FOCAL="$BUNDLER_BIN/extract_focal.pl"
BUNDLER="$BUNDLER_BIN/bundler"
SCRIPTS="$INSTALLS/scripts/scripts"
IMAGE_DIR="."

#printf "\e[1;34m\n\t---------------------------\n\t  Using David Lowe's SIFT\n\t---------------------------\e[0m\n\n"
MATCHKEYS="$BUNDLER_BIN/KeyMatchFull" 
SIFT="$BUNDLER_BIN/sift"
FIND_FEATURES="$SCRIPTS/use_Lowe.sh $IMAGE_DIR $SIFT"

# create the lists of images
printf "\n\033[1mPreprocessing and creating lists....\033[0m\n"
$SCRIPTS/preprocess $IMAGE_DIR $EXTRACT_FOCAL
printf "\e[1;34mDone.\e[0m\n\n"

# generate a list of commands to extract keypoints
printf "\033[1mGenerating the key extraction commands....\033[0m\n"
sh $FIND_FEATURES
printf "\e[1;34mDone.\e[0m\n\n"

# Execute the key extraction commands
printf "\033[1mExtracting the keypoints...\033[0m\n"
sh keypoints.txt
printf "\e[1;34mDone.\e[0m\n\n"

# Match images (can take a while)
printf "\033[1mMatching keypoints (this can take a while)...\033[0m\n"
$SCRIPTS/match $MATCHKEYS 
printf "\e[1;34mDone.\e[0m\n\n"

# Generate the options file for running bundler 
printf "\033[1mRunning Bundler...\033[0m\n"
sh $SCRIPTS/bundling $BUNDLER
printf "\e[1;34mDone.\e[0m\n\n"

# Converting Bundler output to PMVS format
printf "\033[1mConverting Bundler output to PMVS format...\033[0m\n"
$SCRIPTS/pmvs $BUNDLER_BIN $BUNDLE2PMVS
printf "\e[1;34mDone.\e[0m\n\n"

#run cmvs and pmvs2
printf "\033[1mRunning CMVS and PMVS2...\033[0m\n"
$SCRIPTS/cmvs $CMVS
printf "\e[1;34mDone.\e[0m\n\n"

printf "\033[1mMoving results to folder...\033[0m\n"
$SCRIPTS/moving 1
printf "\e[1;34mDone.\e[0m\n\n"

bclean

printf "\033[1mProcessing finished. Do you want to see the resulting mesh? [y/n]\033[0m\n"
read answ
if [ "$answ" = "y" ] ; then 
    $SCRIPTS/viewresult 1
fi

printf "\e[1;34mDone.\e[0m\n\n"

